# Generated by Django 2.2.10 on 2020-07-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='cur_name',
            field=models.CharField(db_index=True, default='RUB', max_length=3, unique=True, verbose_name='Наименование валюты'),
        ),
    ]
