# Generated by Django 2.2.10 on 2020-07-28 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_auto_20200727_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='conversion.Currency', verbose_name='Наименование валюты'),
        ),
    ]
