# Generated by Django 2.2.10 on 2020-07-28 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0003_auto_20200728_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='conversion.Currency', verbose_name='Наименование валюты'),
        ),
    ]
