# Generated by Django 2.2.10 on 2020-07-28 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0004_auto_20200728_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='currency',
            name='destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, verbose_name='Назначение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(max_length=15, verbose_name='Назначение'),
        ),
    ]
