# Generated by Django 2.2.10 on 2020-07-28 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0005_auto_20200728_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='destination',
        ),
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
